### ISSUE TITLE
WAD Woes

### ISSUE THREAD

**Issue by havingfunq** [connect/null-doom#1]
I want to complain that I am about to spend hours manually saving things in png. It would be nice if you included all the png/snd/other files somehow. I understand that may bloat your repository, but its GitHub. It probably will not matter to anyone.

Is there a running copy of this repo somewhere on the web?

Thanks

**Comment by connect** [comment]
Hello. There is one link to have a look http://doom.jscript.eu Just click to lock mouse pointer, hit Esc and use arrows to navigate (new game), hit Enter to start. Ingame hit C to toggle Clipping mode.

Please take this file http://doom.jscript.eu/doom.wad.zip  To compensate your time it also contains converted music.

**Comment by havingfunq** [comment]
Thank you connect! This is an awesome port, by the way,

**Comment by connect** [comment]
Thanks havingfunq!
